app/routes/documents.py
# flake8: noqa
from flask import Blueprint, render_template, request, redirect, url_for, Response
from flask_login import current_user, login_required  # type: ignore
from app.repositories import get_activ_page, get_menu_by_id
from app.repositories import BaseRepository
import csv
from io import StringIO


documents_blueprint = Blueprint('documents', __name__, url_prefix='/documents')
documents_blueprints = {'documents.render_documents':
                        documents_blueprint}


def execute_sql(query, is_select):
    repository = BaseRepository()
    try:
        if is_select:
            return {"type": "table", "data": repository.universal_select(query)}
        else:
            return {"type": "text", "data": repository.universal_querry(query)}
    except Exception as e:
        return {"type": "error", "data": str(e)}


@documents_blueprint.route("/", methods=['GET', 'POST'])
@login_required
def render_documents():
    pages = get_menu_by_id(current_user.get_id())
    query = request.args.get("query", "")  # Получаем параметр query из URL
    if request.method == 'POST':
        is_select = False
        query = request.form.get("sql_query", "").strip()
        if not query:
            return render_template("documents/documents.html", error="Запрос пустой", query=query)

        if query.strip().lower().startswith("select"):
            is_select = True
        result = execute_sql(query, is_select)
        # Обрабатываем результат
        if result["type"] == "error":
            return render_template("documents/documents.html", return_type="error", error=result["data"], active_page=get_activ_page(pages, 'documents.render_documents'), pages=pages, query=query)
        elif result["type"] == "table":
            return render_template("documents/documents.html", return_type="table", data=result["data"], active_page=get_activ_page(pages, 'documents.render_documents'), pages=pages, query=query)
        else:
            return render_template("documents/documents.html", return_type="text", message=result["data"], active_page=get_activ_page(pages, 'documents.render_documents'), pages=pages, query=query)

    return render_template("documents/documents.html", active_page=get_activ_page(pages, 'documents.render_documents'), pages=pages, query=query)

@documents_blueprint.route("/export_csv")
@login_required
def export_csv():
    query = request.args.get("query")
    if not query:
        return "Ошибка: не указан запрос", 400

    is_select = query.strip().lower().startswith("select")
    result = execute_sql(query, is_select)

    if not result or len(result) < 2:
        return "Ошибка: запрос не вернул данных", 400

    # Создаем CSV файл из данных
    output = StringIO()
    writer = csv.writer(output)

    # Пишем данные
    for row in result['data']:
        print(row)
        writer.writerow(row)

    output.seek(0)

    # Возвращаем файл как ответ с правильными заголовками
    return Response(
        output,
        mimetype="text/csv",
        headers={
            "Content-Disposition": "attachment;filename=export.csv"
        }
    )

@documents_blueprint.route("/avalable_vacancies")
@login_required
def avalable_vacancies():
    query = '''
SELECT vacancy.id, vacancy.position_title, vacancy.lower_limit_of_salary, vacancy.upper_limit_of_salary, employer.name AS employer_name
FROM vacancy
JOIN employer ON vacancy.employer_id = employer.id
LEFT JOIN agreement ON vacancy.id = agreement.vacancy_id
WHERE agreement.id IS NULL;
'''
    return redirect(url_for('documents.render_documents', query=query))


@documents_blueprint.route("/no_work_experience")
@login_required
def no_work_experience():
    query = '''
SELECT applicant.id, applicant.last_name, applicant.first_name, applicant.middle_name, applicant.age
FROM applicant
LEFT JOIN specialization_applicant ON applicant.id = specialization_applicant.applicant_id
WHERE specialization_applicant.id IS NULL;
'''
    return redirect(url_for('documents.render_documents', query=query))

@documents_blueprint.route("/no_vacancy")
@login_required
def no_vacancy():
    query = '''
SELECT employer.id, employer.name, employer.phone_number
FROM employer
LEFT JOIN vacancy ON employer.id = vacancy.employer_id
WHERE vacancy.id IS NULL;
'''
    return redirect(url_for('documents.render_documents', query=query))

app/routes/home.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required  # type: ignore
from flask_login import logout_user, current_user  # type: ignore
from werkzeug.security import generate_password_hash, check_password_hash
from app.repositories import get_user_id, add_user, get_user_by_id
from app.repositories import get_activ_page, get_menu_by_id


home_blueprint = Blueprint('home', __name__, url_prefix='/',)
home_blueprints = {'home.render_home': home_blueprint}


@home_blueprint.route("/")
@login_required
def render_home():
    '''Рендер главной страницы'''
    pages = get_menu_by_id(current_user.get_id())
    return render_template("home/home.html",
                           active_page=get_activ_page(pages,
                                                      'home.render_home'),
                           pages=pages)


@home_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        login = request.form['login']
        password = request.form['password']
        hashed_password = generate_password_hash(password)

        try:
            # Проверяем, не занят ли логин
            if get_user_id(login):
                flash('Логин уже занят, выберите другой', 'danger')
                return redirect(url_for('home.register'))

            if len(password) < 8:
                flash('Длина пароля должна быть на меньше 8 симоволов!',
                      'danger')
                return redirect(url_for('home.register'))

            # Добавляем пользователя
            add_user(login, hashed_password)
            flash('Регистрация успешна! Теперь вы можете войти.', 'success')
            return redirect(url_for('home.login'))

        except Exception as e:
            flash(f'Ошибка при регистрации: {e}', 'danger')
            return redirect(url_for('home.register'))

    return render_template('auth/register.html')


@home_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        login = request.form['login']
        password = request.form['password']

        try:
            # Проверяем, существует ли пользователь
            user_id = get_user_id(login)
            if not user_id:
                flash('Пользователь с таким логином не найден', 'danger')
                return redirect(url_for('home.login'))

            # Получаем данные пользователя и проверяем пароль
            user = get_user_by_id(user_id)
            if not check_password_hash(user.password_hash, password):
                flash('Неверное имя пользователя или пароль', 'danger')
                return redirect(url_for('home.login'))

            # Успешный вход
            login_user(user)
            return redirect(url_for('home.render_home'))

        except Exception as e:
            flash(f'Ошибка при обработке запроса: {e}', 'danger')
            return redirect(url_for('home.login'))

    return render_template('auth/login.html')


@home_blueprint.route('/protected')
@login_required
def protected():
    return "This is a protected page."


@home_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home.login'))

app/templates/base/base.html
{# templates/base.html #}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{active_page.name}}</title>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/navigate.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/table.css') }}">
    {% block links %} 
 
    {% endblock links %}

</head>
<body>
    {% include "base/navigate.html" %}
    <a href="{{ url_for('home.logout') }}" class="loginout">
        Выход
    </a>
    </div>
    <main>
        {% block content %} 
        {% endblock content %}      
    </main>
    <div class="logout_box">
        
    <script src="{{url_for('static', filename='js/table.js')}}"></script>
</body>
</html>

app/templates/base/documents_table.html
<table id="table" class="view-mode">
    <thead>
        <tr>
            {% for title in data.0 %}
            <th>
                {{ title }} 
            </th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for entry in data[1:] %}
        <tr>
            {% for i in range(entry|length) %}
                {% if i == 0 %}
                    <td>{{ entry.0 }}</td>
                {% else %}
                    <td><input class="editable" type="text" value="{{ entry[i] }}" disabled></td>
                {% endif%}
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

app/templates/base/editable_table.html
<div class="search-bar">
<form id="search-form" method="get" action="">
    <div class="search-input-container">
        <input
            type="text"
            name="search_query"
            placeholder="Поиск по таблице..."
            value="{{ search_query|default('') }}"
        />
        <button type="submit" onclick="updateSearchQuery(event)">🔍</button>
    </div>
</form>
</div>

<div class="pagination">
    <label for="records-per-page">Записей на странице:</label>
    <select id="records-per-page" onchange="changeRecordsPerPage(this)">
        <option value="5" {% if records_per_page == 5 %}selected{% endif %}>5</option>
        <option value="10" {% if records_per_page == 10 %}selected{% endif %}>10</option>
        <option value="15" {% if records_per_page == 15 %}selected{% endif %}>15</option>
        <option value="20" {% if records_per_page == 20 %}selected{% endif %}>20</option>
    </select>
    <label for="records-per-page">Страница:</label>
    {% for i in range(1, total_pages + 1) %}
        <a href="?page={{ i }}&sort_dir={{ sort_dir }}&records_per_page={{ records_per_page }}&search_query={{ search_query }}&sort_by={{ sort_by }}&view_mode={{ view_mode }}"
           {% if i == current_page %}class="active"{% endif %}>
            {{ i }}
        </a>
    {% endfor %}
</div>

<table id="table" class="view-mode">
    <thead>
        <tr>
            <th></th>
            {% for title in data.0 %}
            <th>
                {{ title }} <br>
                <a href="?sort_by={{ loop.index0 }}&sort_dir=True&records_per_page={{ records_per_page }}&search_query={{ search_query }}&page={{ current_page }}&view_mode={{ view_mode }}">▲</a>
                <a href="?sort_by={{ loop.index0 }}&sort_dir=False&records_per_page={{ records_per_page }}&search_query={{ search_query }}&page={{ current_page }}&view_mode={{ view_mode }}">▼</a>
                {% if current_sort_by == loop.index0 %}
                    {% if current_sort_dir == 'asc' %}
                        <span>▲</span>
                    {% else %}
                        <span>▼</span>
                    {% endif %}
                {% endif %}
            </th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for entry in data[1:] %}
        <tr>
            
            <td>{% if active_page.d %}<button class="delete-row">🗑️</button>{% endif %}</td>
            {% for i in range(entry|length) %}
                {% if i == 0 %}
                    <td>{{ entry.0 }}</td>
                {% else %}
                    <td><input class="editable" type="text" value="{{ entry[i] }}" disabled></td>  
                {% endif %}  
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Кнопки -->
<div class="buttons">
    {% if active_page.w %}<button id="add-row">➕ Добавить запись</button>{% endif %}
    {% if active_page.w or active_page.e %}<button onclick="saveData()">💾 Сохранить все</button>{% endif %}
    {% if active_page.e %}<button onclick="toggleEditMode()">🔄 Переключить режим</button>
    <span id="mode-text">Режим просмотра</span>{% endif %}
</div>

app/templates/base/navigate.html
{% block navigate%}
<div class="container">
    <nav class="menu">
        {% for page in pages %}
            {% if page.have_submenu %}
                <div class="menu-item">
                    <a href="{{ url_for(page.function_name) }}" class="navigate_link">{{ page.name }}</a>
                    <div class="submenu">
                        {% for subpage in page.submenu %}
                        <a href="{{ url_for(subpage.function_name) }}" {% if subpage.function_name == active_page.function_name %} class="active_navigate_link" {% else %} class="navigate_link" {% endif %}>
                            {{ subpage.name }}
                        </a>
                        {% endfor %}
                    </div>
                </div>
            {% elif page.name != pages.0.name %}
                <a href="{{ url_for(page.function_name) }}" {% if page.function_name == active_page.function_name %} class="active_navigate_link" {% else %} class="navigate_link" {% endif %}>
                    {{ page.name }}
                </a>
            {% endif %}
        {% endfor %}
    </nav>
</div>
{% endblock navigate%}

app/templates/base/readonly_table.html
<div class="search-bar">
    <form id="search-form" method="get" action="">
        <div class="search-input-container">
            <input
                type="text"
                name="search_query"
                placeholder="Поиск по таблице..."
                value="{{ search_query|default('') }}"
            />
            <button type="submit" onclick="updateSearchQuery(event)">🔍</button>
        </div>
    </form>
</div>


<div class="pagination">
    <label for="records-per-page">Записей на странице:</label>
    <select id="records-per-page" onchange="changeRecordsPerPage(this)">
        <option value="5" {% if records_per_page == 5 %}selected{% endif %}>5</option>
        <option value="10" {% if records_per_page == 10 %}selected{% endif %}>10</option>
        <option value="15" {% if records_per_page == 15 %}selected{% endif %}>15</option>
        <option value="20" {% if records_per_page == 20 %}selected{% endif %}>20</option>
    </select>
    <label for="records-per-page">Страница:</label>
    {% for i in range(1, total_pages + 1) %}
        <a href="?page={{ i }}&sort_dir={{ sort_dir }}&records_per_page={{ records_per_page }}&search_query={{ search_query }}&sort_by={{ sort_by }}&view_mode={{ view_mode }}"
           {% if i == current_page %}class="active"{% endif %}>
            {{ i }}
        </a>
    {% endfor %}
</div>

<table id="table" class="view-mode">
    <thead>
        <tr>
            {% for title in data.0 %}
            <th>
                {{ title }} <br>
                <a href="?sort_by={{ loop.index0 }}&sort_dir=True&records_per_page={{ records_per_page }}&search_query={{ search_query }}&page={{ current_page }}&view_mode={{ view_mode }}">
                    ▲
                </a>
                <a href="?sort_by={{ loop.index0 }}&sort_dir=False&records_per_page={{ records_per_page }}&search_query={{ search_query }}&page={{ current_page }}&view_mode={{ view_mode }}">
                    ▼
                </a>
                {% if current_sort_by == loop.index0 %}
                    {% if current_sort_dir == 'asc' %}
                        <span>▲</span>
                    {% else %}
                        <span>▼</span>
                    {% endif %}
                {% endif %}
            </th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for entry in data[1:] %}
        <tr>
            {% for i in range(entry|length) %}
                {% if i == 0 %}
                    <td>{{ entry.0 }}</td>
                {% else %}
                    <td><input class="editable" type="text" value="{{ entry[i] }}" disabled></td>
                {% endif%}
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

app/templates/base/table.html
<div class="controls">
    <label for="records-per-page">Записей на странице:</label>
    <select id="records-per-page" onchange="changeRecordsPerPage(this)">
        <option value="5" {% if records_per_page == 5 %}selected{% endif %}>5</option>
        <option value="10" {% if records_per_page == 10 %}selected{% endif %}>10</option>
        <option value="15" {% if records_per_page == 15 %}selected{% endif %}>15</option>
        <option value="20" {% if records_per_page == 20 %}selected{% endif %}>20</option>
    </select>
    <button onclick="toggleEditMode()">Переключить режим</button>
    <span id="mode-text">Режим просмотра</span>
</div>
<div class="pagination">
    {% if current_page > 1 %}
        <a href="?page={{ current_page - 1 }}&records_per_page={{ records_per_page }}">Назад</a>
    {% endif %}
    {% for i in range(1, total_pages + 1) %}
        <a href="?page={{ i }}&records_per_page={{ records_per_page }}" {% if i == current_page %}class="active"{% endif %}>{{ i }}</a>
    {% endfor %}
    {% if current_page < total_pages %}
        <a href="?page={{ current_page + 1 }}&records_per_page={{ records_per_page }}">Вперед</a>
    {% endif %}
</div>
<table id="table" class="view-mode">
    <thead>
        <tr>
            <th></th>
            {% for title in data.0 %}
            <th>
                {{ title }}
                <a href="?sort_by={{ loop.index0 }}&sort_dir=True">
                    ▲
                </a>
                <a href="?sort_by={{ loop.index0 }}&sort_dir=False">
                    ▼
                </a>
                {% if current_sort_by == loop.index0 %}
                    {% if current_sort_dir == 'asc' %}
                        <span>▲</span>
                    {% else %}
                        <span>▼</span>
                    {% endif %}
                {% endif %}
            </th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for entry in data[1:] %}
        <tr>
            <td><button class="delete-row">Удалить</button></td>
            {% for i in range(entry|length) %}
                {% if i == 0 %}
                    <td>{{ entry.0 }}</td>
                {% else %}
                    <td><input class="editable" type="text" value="{{ entry[i] }}" disabled></td>
                {% endif%}
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
<button id="add-row">Добавить строку</button>
<button onclick="saveData()">Сохранить изменения</button>

app/templates/base/table_page.html
<div class="header-wrapper">
    <h1>{{active_page.name}}</h1>
    <div class="view-mode-switch">
        {% if request.args.get('view_mode', 'readonly') == 'readonly' %}
            <a href="?view_mode=editable{% for key, value in request.args.items() if key != 'view_mode' %}&{{ key }}={{ value }}{% endfor %}">
                <button class="emodji_button">✏️</button>
            </a>
        {% else %}
            <a href="?view_mode=readonly{% for key, value in request.args.items() if key != 'view_mode' %}&{{ key }}={{ value }}{% endfor %}">
                <button class="emodji_button">📖</button>
            </a>
        {% endif %}
    </div>
    
</div>

{% if request.args.get('view_mode', 'readonly') == 'editable' %}
    {% include "base/editable_table.html" %}
{% else %}
    {% include "base/readonly_table.html" %}
{% endif %}